from typing import List, Dict

default_classifications:List[Dict[str,str]] = [
            {'field':'active_account','classification':'target'},
            {'field':'delinquent_account','classification':'target'},
            {'field':'ident_monitor_opt','classification':'actionable'},
            {'field':'Num_Bk_Accts','classification':'actionable'},
            {'field':'income','classification':'actionable'},
            {'field':'bk_accts_ssn','classification':'actionable'},
            {'field':'cells_ssn','classification':'actionable'},
            {'field':'dls_ssn','classification':'actionable'},
            {'field':'emails_ssn','classification':'actionable'},
            {'field':'hmphones_ssn','classification':'actionable'},
            {'field':'addrs_ssn','classification':'actionable'},
            {'field':'ssn_ssn','classification':'actionable'},
            {'field':'zips_ssn','classification':'actionable'},
            {'field':'empl_ssn_6Mo','classification':'actionable'},
            {'field':'pday_inq_15days','classification':'actionable'},
            {'field':'dti_score','classification':'actionable'},
            {'field':'days_from_registration','classification':'actionable'},
            {'field':'days_from_login','classification':'actionable'},
            {'field':'asset_score','classification':'actionable'},
            {'field':'alt_risk_score','classification':'actionable'},
            {'field':'seg_id','classification':'actionable'},
            {'field':'stability_score','classification':'actionable'},
            {'field':'max_bkaccts','classification':'actionable'},
            {'field':'auto_inq_1dy','classification':'actionable'},
            {'field':'auto_inq_7dy','classification':'actionable'},
            {'field':'auto_inq_72hr','classification':'actionable'},
            {'field':'cc_inq_72hr','classification':'actionable'},
            {'field':'cc_inq_10dy','classification':'actionable'},
            {'field':'pl_inq_72hr','classification':'actionable'},
            {'field':'pl_inq_90dy','classification':'actionable'},
            {'field':'alt_risk_score_2','classification':'actionable'},

        ]